nginx:
  location_avatar: D:\nginx\nginx-1.27.0\html\avatar
  location_patent: D:\nginx\nginx-1.27.0\html\patent
  location_article: D:\nginx\nginx-1.27.0\html\article
  location_trademark: D:\nginx\nginx-1.27.0\html\trademark
  url: http://127.0.0.1:9000